# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVball1register():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_vball1register(self):
    # Test name: vball1register
    # Step # | name | target | value | comment
    # 1 | open | /b/book/volleyball-i?step=calendar&s=ybpxjllvk3zl67ykdx4jpgjiiefa3x |  | 
    self.driver.get("https://anny.co/b/book/volleyball-i?step=calendar&s=ybpxjllvk3zl67ykdx4jpgjiiefa3x")
    # 2 | setWindowSize | 848x912 |  | 
    self.driver.set_window_size(848, 912)
    # 3 | click | css=.selectable > .date-item-inner |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".selectable > .date-item-inner").click()
    # 4 | click | css=.eb-btn > span:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".eb-btn > span:nth-child(1)").click()
  
